import Head from 'next/head'
import { useEffect, useState } from 'react';
import Layout from '../../hoc/Layout/Layout';

import Navigation from '../../components/Navigation/Navigation';
import Intro from '../../container/Intro/Intro';
import Features from '../../container/Features/Features';
import Plans from '../../container/Plans/Plans';
import GetStarted from '../../container/GetStarted/GetStarted';
import Testimonial from '../../container/Testimonial/Testimonial';
import Footer from '../../components/Footer/Footer';

import Loader from '../../components/Loader/Loader';


export default function HomePage() {
  const [loading,setLoading] = useState(true);

  useEffect(() => {
    if(loading){
      setTimeout(function(){
        setLoading(false);
      },2000)
    }
   
  },[loading,setLoading]);

  return (
    <>
      <Head>
        <title>Peddle Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>

        {loading ? <Loader /> : (
        <>
        <Navigation />
        <main className="main--contain">
          <Intro  />
            {/* FEATURES SECTION */}
          <Features  />
               {/* PRICING/PLAN SECTION */}
          <Plans />
              {/* GET STARTED SECTION */}
          <GetStarted  />
               {/* TESTIMONIAL SECTION */}
          <Testimonial />
        </main>

        <Footer />
        </>)}

        </Layout> 
    </>
  )
}
